import React from 'react';

import Head from 'next/head'
import { useRouter } from 'next/router';

import nookies from 'nookies'

import styles from '../../styles/Posts.module.css'
import Link from 'next/link';


export async function getServerSideProps(ctx){

  const COOKIES = nookies.get(ctx)

  const SECRET_PASSWORD = '123456'
  const INPUT_PASSWORD = COOKIES.INPUT_PASSWORD

  const isAutheticated = SECRET_PASSWORD === INPUT_PASSWORD

  if(!isAutheticated){
    return {
      redirect: {
        permanent: false,
        destination: '/?status=401'
      }
    }
  }

  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const posts = await res.json()

  return {
    props: {
      posts: posts
    }
  }
}


export default function Posts({ posts }) {

  const router = useRouter()

  return (
    <>
      <Head>
        <title>Posts | Nookies SSR & API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <nav className={styles.nav}>
            <h2>Hello user, nice to see you again! :)</h2>
            <button 
              className={styles.button}
              onClick={e => {
                e.preventDefault()
                nookies.destroy(null, 'INPUT_PASSWORD')
                router.push('/')
              }}>
                Logout
            </button>
          </nav>
          <div className={styles.posts}>
            <h2>See the latest posts</h2>
            <ul>
              {posts?.map(post => (
                <li>
                  <Link href={`/posts/${post.id}`}>{post.title}</Link>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </main>
    </>
  );
}