import React, { useState } from 'react'

import Head from 'next/head'
import { useRouter } from 'next/router'

import nookies from 'nookies'

import styles from '../styles/Home.module.css'

export default function Home() {

  const router = useRouter()
  const [ password, setPassword ] = useState('')

  return (
    <>
      <Head>
        <title>Pagina Inicial | Nookies SSR & API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <form 
            id='form'
            className={styles.form}
            method="post"
            onSubmit={(e) => {
              e.preventDefault()
              if(!!password){
                nookies.set(null, 'INPUT_PASSWORD', password, {
                  maxAge: 24 * 60 * 60, // 24HRS
                  path: '/'
                })

                router.push('/posts')
              }
              else {
                alert('Informe uma senha valida !')
              }
            }}>
            <label htmlFor="password" className={styles.label}>Insira sua senha</label>
            <input 
              type="text" 
              name="password" 
              id="password" 
              className={styles.input}
              placeholder="******"
              value={password}
              onChange={e => setPassword(e.target.value)}
            />
          </form>
          <button className={styles.button} type='submit' form='form'>
            Acessar
          </button>
        </div>
      </main>
    </>
  )
}
